# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['src/pst2mbox/cli.py'],
    pathex=['src'],
    binaries=[],
    datas=[('README.md', '.'), ('LICENSE', '.'), ('assets/icon.ico', 'assets')],
    hiddenimports=[
        'pst2mbox',
        'pst2mbox.converter',
        'pst2mbox.header_helper',
        'pst2mbox.cli',
        'pypff',
        'striprtf',
        'striprtf.striprtf',
        'email.mime.multipart',
        'email.mime.text',
        'email.mime.base',
        'email.encoders',
        'email.header',
        'email.utils',
        'mailbox',
        'pathlib',
        'argparse',
        'logging',
        'time',
        'datetime',
        'base64',
        'mimetypes',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'scipy',
        'numpy',
        'torch',
        'torchvision',
        'pandas',
        'PIL',
        'IPython',
        'notebook',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='pst2mbox',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='assets/icon.ico',
)
